### ISSUE TITLE
null error

### ISSUE THREAD

**Issue by madtomic** [Agazed/WorldLoad#1]
http://pastebin.com/f6ykEqxH

When trying to use this /wl create testworld

It gives error on console.

**Comment by madtomic** [comment]
This is  WorldLoad 2.0

**Comment by Agazed** [comment]
Do you have a nether world?

**Comment by madtomic** [comment]
I disabled nether and end.

**Comment by Agazed** [comment]
Should be fixed now. Tell me if you get the same error with 2.1 on Bukkit.
